### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by icyfox168168** [lasarus/Assembler#1]
This project does not work well in windows, do you plan to continue to maintain this project? I currently use yasm to generate obj, and then tcc to generate exe files

**Comment by lasarus** [comment]
I don't plan on maintaining it as a separate project. I will eventually merge it into my C compiler.

**Comment by icyfox168168** [comment]
When will it be integrated into the compiler, I am looking forward to it, I don’t need yasm anymore

**Comment by lasarus** [comment]
It will be at least a couple of weeks until I get around to it. I need to change some things in the compiler first.
